/**
 * content-monitor runner. Weekly, deterministic, no model calls.
 * Work is generated by drift, not by a planning meeting.
 *
 * Corpus assembly: published documents come from Payload over REST when
 * PAYLOAD_URL is set (production); otherwise from .agency/content/published/
 * (the local mirror used before deploy and in tests). Staged drafts are
 * always read from .agency/content/drafts/.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { parse as parseYaml } from 'yaml';
import { loadBrand, loadBrief, listBriefSlugs, repoPaths } from '../../../packages/content-pipeline/src/artifacts';
import { arg } from '../../../packages/content-pipeline/src/cliArgs';
import type { BriefArtifact, PackArtifact } from '../../../packages/content-pipeline/src/gates/types';
import {
  checkBriefAndPack,
  checkDecay,
  checkExternalLinks,
  checkInternalLinkGraph,
  checkMustSupportStillResolves,
  checkPositioningHash,
  checkPublishedHasReview,
  checkSourceFreshness,
  type CorpusDoc,
  type Violation,
} from './invariants';
import { Triage } from './triage';

const readJsonDir = <T>(dir: string): T[] => {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(path.join(dir, f), 'utf8')) as T);
};

const fetchPublishedFromPayload = async (baseUrl: string, apiKey: string): Promise<CorpusDoc[]> => {
  const docs: CorpusDoc[] = [];
  const base = baseUrl.replace(/\/$/, '');
  for (const collection of ['posts', 'recipes'] as const) {
    let page = 1;
    for (;;) {
      if (page > 500) throw new Error(`payload fetch ${collection}: exceeded 500 pages`);
      const res = await fetch(
        `${base}/api/${collection}?where[_status][equals]=published&limit=100&page=${page}`,
        { headers: { Authorization: `users API-Key ${apiKey}` } },
      );
      if (!res.ok) throw new Error(`payload fetch ${collection}: ${res.status}`);
      const body = (await res.json()) as {
        docs: Record<string, unknown>[];
        hasNextPage?: boolean;
        totalPages?: number;
      };
      for (const d of body.docs) {
        docs.push({
          slug: d.slug as string,
          surface: collection === 'recipes' ? 'recipes' : 'blog',
          content: d.content as CorpusDoc['content'],
          publishedAt: (d.publishedAt ?? d.updatedAt) as string,
          lastReviewedAt: d.lastReviewedAt as string | undefined,
          positioningHash: d.positioningHash as string | undefined,
        });
      }
      if (body.docs.length === 0) break;
      if (body.hasNextPage === true) {
        page += 1;
        continue;
      }
      if (typeof body.totalPages === 'number' && page < body.totalPages) {
        page += 1;
        continue;
      }
      // No pagination metadata: stop when a page returns fewer than the page size.
      if (body.docs.length < 100) break;
      page += 1;
    }
  }
  return docs;
};

const main = async () => {
  const root = path.resolve(arg('root', process.cwd())!);
  const paths = repoPaths(root);
  const brand = loadBrand(paths);
  const external = arg('external-links', process.env.CI ? 'check' : 'skip');

  const published: CorpusDoc[] =
    process.env.PAYLOAD_URL && process.env.CONTENT_AGENT_API_KEY
      ? await fetchPublishedFromPayload(process.env.PAYLOAD_URL, process.env.CONTENT_AGENT_API_KEY)
      : readJsonDir<CorpusDoc>(path.join(paths.content, 'published'));

  const drafts = readJsonDir<CorpusDoc>(path.join(paths.content, 'drafts'));
  const corpus = [...published, ...drafts.filter((d) => !published.some((p) => p.slug === d.slug))];

  const briefSlugs = listBriefSlugs(paths);
  const briefs: BriefArtifact[] = briefSlugs.map((s) => loadBrief(paths, s));
  const packsDir = path.join(paths.content, 'packs');
  const packs: PackArtifact[] = existsSync(packsDir)
    ? readdirSync(packsDir)
        .filter((f) => f.endsWith('.yaml'))
        .map((f) => parseYaml(readFileSync(path.join(packsDir, f), 'utf8')) as PackArtifact)
    : [];

  const reviewsDir = path.join(paths.content, 'reviews');
  const reviewSlugs = existsSync(reviewsDir)
    ? readdirSync(reviewsDir)
        .filter((f) => f.endsWith('.yaml'))
        .map((f) => f.replace(/\.yaml$/, ''))
    : [];

  const violations: Violation[] = [
    ...checkBriefAndPack(published, briefSlugs, packs.map((p) => p.slug), corpus.map((c) => c.slug)),
    ...checkPublishedHasReview(published, reviewSlugs),
    ...checkTargetQueryUniquenessSafe(briefs),
    ...checkInternalLinkGraph(corpus),
    ...(external === 'check' ? await checkExternalLinks(corpus, packs, fetch) : []),
    ...checkSourceFreshness(packs, brand.claimPolicy),
    ...checkPositioningHash(corpus, brand.positioning.hash),
    ...checkDecay(corpus, brand.surfaces),
    ...checkMustSupportStillResolves(corpus, packs),
  ];

  const triage = new Triage(root);
  let filed = 0;
  let duplicates = 0;
  for (const v of violations) {
    const outcome = triage.fileViolation(v.invariant, v.page, v.title, v.evidence);
    if (outcome === 'filed') filed += 1;
    else duplicates += 1;
  }

  console.log(
    `content-monitor: ${corpus.length} document(s), ${briefs.length} brief(s) — ${violations.length} violation(s); ${filed} filed, ${duplicates} already open`,
  );
  for (const v of violations) console.log(`  [${v.invariant}] ${v.title}`);
  if (external !== 'check') console.log('  (external link resolution skipped — offline run)');
};

// import placed here to keep the invariant list readable above
import { checkTargetQueryUniqueness as checkTargetQueryUniquenessSafe } from './invariants';

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
