/**
 * content-monitor runner. Weekly, deterministic, no model calls.
 * Work is generated by drift, not by a planning meeting.
 *
 * Corpus assembly: published documents come from the content-store when
 * PAYLOAD_URL is set (production); otherwise from the local published mirror
 * under the team's artifacts directory. Staged drafts are always read from
 * the local drafts directory.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { parse as parseYaml } from 'yaml';
import { loadBrand, loadBrief, listBriefSlugs, repoPaths } from '@carinyaparc/content-pipeline';
import { arg } from '@carinyaparc/content-pipeline';
import type { BriefArtifact, PackArtifact } from '@carinyaparc/content-pipeline';
import { createPayloadStore } from '@carinyaparc/content-store-payload';
import {
  checkBriefAndPack,
  checkDecay,
  checkExternalLinks,
  checkInternalLinkGraph,
  checkMustSupportStillResolves,
  checkPositioningHash,
  checkPublishedHasReview,
  checkSourceFreshness,
  type CorpusDoc,
  type Violation,
} from './invariants';
import { Triage } from './triage';

const readJsonDir = <T>(dir: string): T[] => {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(path.join(dir, f), 'utf8')) as T);
};

const fetchPublishedFromStore = async (baseUrl: string, apiKey: string): Promise<CorpusDoc[]> => {
  const store = createPayloadStore({ baseUrl, apiKey });
  const published = await store.listPublished();
  return published.map((d) => ({
    slug: d.slug,
    surface: d.collection === 'recipes' ? 'recipes' : 'blog',
    content: d.content,
    publishedAt: d.publishedAt ?? '',
    lastReviewedAt: d.lastReviewedAt,
    positioningHash: d.positioningHash,
  }));
};

const main = async () => {
  const root = path.resolve(arg('root', process.cwd())!);
  const paths = repoPaths(root);
  const brand = loadBrand(paths);
  const external = arg('external-links', process.env.CI ? 'check' : 'skip');

  const published: CorpusDoc[] =
    process.env.PAYLOAD_URL && process.env.CONTENT_AGENT_API_KEY
      ? await fetchPublishedFromStore(process.env.PAYLOAD_URL, process.env.CONTENT_AGENT_API_KEY)
      : readJsonDir<CorpusDoc>(path.join(paths.content, 'published'));

  const drafts = readJsonDir<CorpusDoc>(path.join(paths.content, 'drafts'));
  const corpus = [...published, ...drafts.filter((d) => !published.some((p) => p.slug === d.slug))];

  const briefSlugs = listBriefSlugs(paths);
  const briefs: BriefArtifact[] = briefSlugs.map((s) => loadBrief(paths, s));
  const packsDir = path.join(paths.content, 'packs');
  const packs: PackArtifact[] = existsSync(packsDir)
    ? readdirSync(packsDir)
        .filter((f) => f.endsWith('.yaml'))
        .map((f) => parseYaml(readFileSync(path.join(packsDir, f), 'utf8')) as PackArtifact)
    : [];

  const reviewsDir = path.join(paths.content, 'reviews');
  const reviewSlugs = existsSync(reviewsDir)
    ? readdirSync(reviewsDir)
        .filter((f) => f.endsWith('.yaml'))
        .map((f) => f.replace(/\.yaml$/, ''))
    : [];

  const violations: Violation[] = [
    ...checkBriefAndPack(published, briefSlugs, packs.map((p) => p.slug), corpus.map((c) => c.slug)),
    ...checkPublishedHasReview(published, reviewSlugs),
    ...checkTargetQueryUniquenessSafe(briefs),
    ...checkInternalLinkGraph(corpus),
    ...(external === 'check' ? await checkExternalLinks(corpus, packs, fetch) : []),
    ...checkSourceFreshness(packs, brand.claimPolicy),
    ...checkPositioningHash(corpus, brand.positioning.hash),
    ...checkDecay(corpus, brand.surfaces),
    ...checkMustSupportStillResolves(corpus, packs),
  ];

  const triage = new Triage(root);
  let filed = 0;
  let duplicates = 0;
  for (const v of violations) {
    const outcome = triage.fileViolation(v.invariant, v.page, v.title, v.evidence);
    if (outcome === 'filed') filed += 1;
    else duplicates += 1;
  }

  console.log(
    `content-monitor: ${corpus.length} document(s), ${briefs.length} brief(s) — ${violations.length} violation(s); ${filed} filed, ${duplicates} already open`,
  );
  for (const v of violations) console.log(`  [${v.invariant}] ${v.title}`);
  if (external !== 'check') console.log('  (external link resolution skipped — offline run)');
};

// import placed here to keep the invariant list readable above
import { checkTargetQueryUniqueness as checkTargetQueryUniquenessSafe } from './invariants';

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
